In [102]:
from torch.utils.data import Dataset, DataLoader
import numpy as np

class TimeSeriesSlidingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, prediction_horizon=1):
        self.X = X
        self.y = y
        self.window_size = window_size
        self.prediction_horizon = prediction_horizon - 1
        self.shape = self.__getshape__()

    def __len__(self):
        return len(self.y) - self.window_size

    def __getitem__(self, index):
        return (self.X[:, index:index+self.window_size], self.y[np.newaxis, index+self.window_size+self.prediction_horizon, np.newaxis])

    def __getshape__(self):
        return (self.__len__(), *self.__getitem__(0)[0].shape)

import pandas as pd
import torch

def build_dataset(window_size, prediction_horizon, data_path='input_data.csv'):
    data = pd.read_csv(data_path, index_col=0).iloc[::-1].reset_index(drop=True)
    X = torch.tensor(data.values).reshape(data.shape[1], data.shape[0])
    y = torch.tensor(data['close'].values)

    return TimeSeriesSlidingWindowDataset(X, y, window_size, prediction_horizon)
    

In [41]:
data = pd.read_csv('input_data.csv', index_col=0)
data

open    high     low   close  volume
date                                                       
2020-10-22 20:00:00  426.30  426.58  426.30  426.49  5786.0
2020-10-22 19:59:00  426.69  426.69  426.25  426.50  6459.0
2020-10-22 19:58:00  426.39  426.67  426.37  426.67  3597.0
2020-10-22 19:57:00  426.40  426.50  426.40  426.50  4659.0
2020-10-22 19:56:00  426.30  426.40  426.30  426.40  1062.0
...                     ...     ...     ...     ...     ...
2020-10-09 04:06:00  430.75  430.75  430.75  430.75   291.0
2020-10-09 04:05:00  430.21  430.51  430.20  430.51  1272.0
2020-10-09 04:04:00  430.43  430.43  430.32  430.32   873.0
2020-10-09 04:02:00  430.37  430.43  430.37  430.43  1016.0
2020-10-09 04:01:00  429.75  430.74  429.75  430.11  2083.0

[8186 rows x 5 columns]

In [97]:
data = pd.read_csv('input_data.csv', index_col=0)
data = data.iloc[::-1].reset_index(drop=True)
data.values.shape

(8186, 5)

In [103]:
dataset = build_dataset(2, 1)
trainloader = DataLoader(dataset, batch_size=1, shuffle=False)

torch.Size([5, 8186])
torch.Size([5, 8186])
torch.Size([5, 2])
tensor([[ 429.7500,  430.7400],
        [ 445.4900,  445.4900],
        [ 449.2500,  449.2500],
        [ 446.6600, 1411.0000],
        [3146.0000,  421.0200]], dtype=torch.float64)


In [104]:
for x, y in trainloader:
    print(x.shape)
    print(y.shape)

[ 446.0000,  446.0000],
        [ 446.0000,  446.0000],
        [ 448.4000,  448.6000],
        [ 421.0000, 2246.0000]], dtype=torch.float64)
torch.Size([1, 0, 8186])
torch.Size([1, 1, 1])
torch.Size([5, 8186])
torch.Size([5, 2])
tensor([[ 430.5400,  430.7000],
        [ 446.0000,  446.0000],
        [ 446.0000,  446.0000],
        [ 448.6000, 1230.0000],
        [2246.0000,  420.8900]], dtype=torch.float64)
torch.Size([1, 0, 8186])
torch.Size([1, 1, 1])
torch.Size([5, 8186])
torch.Size([5, 2])
tensor([[ 430.7000,  430.5300],
        [ 446.0000,  446.0000],
        [ 446.0000, 1536.0000],
        [1230.0000,  448.5000],
        [ 420.8900,  420.8900]], dtype=torch.float64)
torch.Size([1, 0, 8186])
torch.Size([1, 1, 1])
torch.Size([5, 8186])
torch.Size([5, 2])
tensor([[ 430.5300,  430.7000],
        [ 446.0000,  748.0000],
        [1536.0000,  446.0000],
        [ 448.5000,  448.6000],
        [ 420.8900,  420.8900]], dtype=torch.float64)
torch.Size([1, 0, 8186])
torch.Size([1, 1, 1])
t

KeyboardInterrupt: 